### ISSUE TITLE
ExecutionEngineException

### ISSUE THREAD

**Issue by aviatrix** [darrenkopp/libsass-net#16]
Hello, 

I'm currently using LibsassNet & web and from on random occasions i see that an ```Unknown error occurred``` is thrown in the C# part of the project, and the scss isn't compiled, however if i refresh the page it's all ok again and after few more refreshes it's broken.

Unfortunately i was not able to find a reliable way to reproduce this 
However i did some debugging on the C++ project and it throws this exception on line 93 
```int result = sass_compile_file(ctx);``` in ```SassInterface.cpp```

Any help with this issue, because i'm looking to use this library in production website in few months.

**Comment by samrueby** [comment]
I actually noticed this too which caused me to roll back to the previous version. I thought it may have been because (in my case) the Sass compiler isn't thread safe.

**Comment by darrenkopp** [comment]
yeah, i think things got broke in 3.1 of libsass. there's a new api, but i'm still using the old api, and I don't think it works properly. I'm working on porting to the new api currently

**Comment by aviatrix** [comment]
Hey Darren
Do you have any ETA on this?

Also, I'm looking at  https://github.com/sass/node-sass/tree/master/src and node-sass are keeping up to date with libsass and  have similar wrappers.
Maybe you can just moddify the wrappers a bit or just use wrapper implementation with .net ?

**Comment by aviatrix** [comment]
This is fixed as of #19
