### ISSUE TITLE
LibSass 3.2 support

### ISSUE THREAD

**Issue by willemdewit** [darrenkopp/libsass-net#22]
Is this library compatible with [LibSass 3.2](https://github.com/sass/libsass/releases/tag/3.2.2)?

**Comment by aviatrix** [comment]
@willemdewit the libsass-net currently supports libsass 3.2-beta5 , the next nuget version release should support 3.2 at least or 3.2.2

**Comment by aviatrix** [comment]
@willemdewit Please update your version of LibSassnet & libsassnet.web, they now support libsass 3.2.2
