### ISSUE TITLE
The handle is invalid

### ISSUE THREAD

**Issue by JimBobSquarePants** [darrenkopp/libsass-net#26]
Just upgraded to v3.2.4 and am now getting the following error.

>The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

Thrown on.

```
ISassCompiler.Compile();
```

Not sure what else you'll need from me.

**Comment by darrenkopp** [comment]
Fix coming soon, stuck in the backwoods right now with limited internet

**Comment by darrenkopp** [comment]
just deployed the fix for this to nuget.

**Comment by JimBobSquarePants** [comment]
Sweet. Well done!
