### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by dszczepanska** [darrenkopp/libsass-net#27]
Hello, it's my action in asp.net mvc:

string scss = @"@import """ + Server.MapPath(scssPath) + @""";";
            var compiler = new SassCompiler();
            //string compiled = compiler.Compile(source: scss); //returns "button.button {background-color:#ffffff;}button.button:hover {opacity:0.5;}"
            var compiled = compiler.Compile(scss);

I have the error  
An exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.dll but was not handled in user code

Additional information: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

What can be reason for it?

**Comment by darrenkopp** [comment]
Yeah. Fix coming soon

**Comment by darrenkopp** [comment]
Just deployed the fix for this to nuget.
