### ISSUE TITLE
3.2.4.1 broke source maps

### ISSUE THREAD

**Issue by madskristensen** [darrenkopp/libsass-net#30]
The latest release broke the source map generation. `CompileFileResult.SourceMap` is null after running the compiler with either an absolute or relative path parameter for the source map file

**Comment by darrenkopp** [comment]
Thanks for reporting, I can repro the problem but haven't been able to resolve it yet this morning. Will look into it more this evening.

**Comment by madskristensen** [comment]
Awesome. Thanks. No rush

**Comment by darrenkopp** [comment]
fixed, also upgraded to 3.2.5 of libsass.

**Comment by madskristensen** [comment]
You sir, are awesome. Thank you
