### ISSUE TITLE
Compile multiple files and change variable by coding

### ISSUE THREAD

**Issue by sonphnt** [darrenkopp/libsass-net#38]
Hi all,

Can we change a variable and also combine all sass files into one and then generate a file css file ?

For example I want to change @body-color that depending on my setting in database and a css file should be generated base on that color.

Thanks

**Comment by janzii** [comment]
We do it something like this in our project:

c# code
```c#
string sass = "$color: #123456;\n"
+ "@import \"template\";";

var compiler = new LibSassNet.SassCompiler();
var css = compiler.Compile(sass, outputStyle: LibSassNet.OutputStyle.Nested, includeSourceComments: true, includePaths: new[] { Server.MapPath("~/Content/sass") });
```

_template.scss
```css
body {
    background-color: $color;
}
```
