### ISSUE TITLE
Processor Architecture warning

### ISSUE THREAD

**Issue by BarryFogarty** [darrenkopp/libsass-net#39]
Hi,

I've been trying to get this library working via another project which consumes it (https://github.com/JimBobSquarePants/Cruncher), but it fails at runtime and the following warning is reported in Visual Studio 2012:

Warning There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "libsassnet, Version=1.0.0.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

More detials on the runtime error are reported here https://github.com/JimBobSquarePants/Cruncher/issues/28

**Comment by darrenkopp** [comment]
Are you referencing libsass.x86 or libsass.x64?

**Comment by BarryFogarty** [comment]
libsass.x64

**Comment by darrenkopp** [comment]
And you definitely installed Visual C++ 2013 redist for x64? Not the 2012 one? That warning always appears when you choose MSIL but are referencing an assembly that has been compiled for a specific platform.

**Comment by BarryFogarty** [comment]
Yep pretty sure I have the right redist installed:

<img width="656" alt="screenshot 2015-11-24 09 05 42" src="https://cloud.githubusercontent.com/assets/2164279/11362498/dfb2d042-928b-11e5-8147-323808429482.png">

**Comment by ericrovtar** [comment]
I'm seeing this too with v2.1.3. If I try to upgrade the NuGet package to 2.1.3.1 it will build and throw the same warnings, but pages won't load. At least with v2.1.3, pages are still loading.

I have the Visual C++ 2013 Redistributable installed (both 32 & 64 bit):
![capture](https://cloud.githubusercontent.com/assets/3474545/13254274/a5dffd52-da0e-11e5-8441-c854fbd5729c.PNG)

As @BarryFogarty said, maybe the other packages are conflicting, though I haven't manually installed any of these. They've been installed by apps like Visual Studio and SQL Express, so I'm hesitant to remove any of them.

Any thoughts?

**Comment by darrenkopp** [comment]
Not sure if this is still an issue or not, but the new packages (alpha on nuget) released today are all MSIL for the .net assemblies, though you'll still need the redistributables for libsass
