### ISSUE TITLE
Error: File to read not found or unreadable

### ISSUE THREAD

**Issue by Skeldave** [darrenkopp/libsass-net#41]
Hi,

I am trying to read a SASS file from a network location and it is throwing the following error: 

"Error: File to read not found or unreadable: \\\\\\\PATH\\\TO\\\SASS\\\FOLDER\\\SASS.scss\n"

I am using the following configurations:

 var sassCompiler = new SassCompiler();
 var scss = sassCompiler.CompileFile(targetScssFile, OutputStyle.Compact);

I have tried using the same code on a local folder (D:\\PATH\\TO\\SASS) and it works perfectly well.

Please could you give me any pointers / try and test this from your end and let me know the results. 

Thanks.

**Comment by darrenkopp** [comment]
Yeah, unfortunately libsass (the library we wrap) doesn't work with unc
paths for the version we work with. It may have been resolved by now, but
there are some incompatibilities that haven't been resolved yet that
prevent us from using latest version of libsass at the moment.
