### ISSUE TITLE
Takes minutes to compile

### ISSUE THREAD

**Issue by snorrekim** [darrenkopp/libsass-net#46]
Using latest stable build 2.1.3.1:

Every reload of the webpage uses an enormous amount of time on the .scss files. A 300 line file takes 3-10 second (varies videly), and bootstrap takes several minutes.

Bootstrap uses around 1.1 minute, (comparably, it takes around 1.5 seconds with LESS and dotless)

![image](https://cloud.githubusercontent.com/assets/5329330/19772968/1ed28538-9c68-11e6-8457-748d6a0dab92.png)

**Comment by aviatrix** [comment]
Use the Alpha & beta versions. the "Stable" versions are unstable. 
https://www.nuget.org/packages/libsassnet.Web/2.3.0-alpha-1
and 
https://www.nuget.org/packages/libsassnet/3.3.7-alpha-2

**Comment by snorrekim** [comment]
Thank you! That worked. Now it's actually 10 times faster than our LESS compilator. Any idea when this is out of alpha?

Maybe you should mention this in the README.md? https://github.com/darrenkopp/libsass-net

**Comment by aviatrix** [comment]
@darrenkopp do you have time to push those as proper versions?

**Comment by darrenkopp** [comment]
the latest version is in stable channel on nuget now.
