### ISSUE TITLE
Combining the two platform builds.

### ISSUE THREAD

**Issue by JimBobSquarePants** [darrenkopp/libsass-net#9]
Hi there,

Have you considered embedding the two c++ binaries as a resource and delivering the correct one based on processor architecture on demand? That would save having to maintain two libraries and make it easier for people to consume the library.

**Comment by JimBobSquarePants** [comment]
@darrenkopp Hey chum, did you ever get anywhere with this? I'm looking to do some updates to Cruncher but if you have a new release coming soon I will wait for that.

**Comment by darrenkopp** [comment]
yeah we were talking about it over here: https://github.com/darrenkopp/libsass-net/issues/13#issuecomment-76645126. i'm gonna attempt to get pure libsass using that solution file, then it's just a matter of updating to the new api and p/invoking.

updates coming soon, trying to get taxes done at the moment

**Comment by JimBobSquarePants** [comment]
Awesome! :smile: I'll hold out then. Cheers!

**Comment by Woland2k** [comment]
Any update on this? Seems like a very big issue especially for microsoft cloud/azure since free one only supports 32bit deployment while basic plan support 64.

**Comment by darrenkopp** [comment]
in progress. you can however use it on both 32-bit and 64-bit currently, you just aren't able to deploy to both simultaneously, you have to know which you are using and install that specific platform version

**Comment by Woland2k** [comment]
Great, yeah I know that I can compile the specific version to deploy to. However we have developers using both 64 and 32 bit machines.

**Comment by Woland2k** [comment]
Any update or direction you going to take in implementing this? We can help with implementation if needed.

**Comment by darrenkopp** [comment]
basically drop the managed c++ (ala https://github.com/darrenkopp/libsass-net/tree/pinvoke) and then use p/invoke for everything. Once all the methods / structs are mapped, then it's a simple matter of doing

```
if (IntPtr.Size == 4) { Run32BitMethod(); } else { Run64BitMethod(); }
```

**Comment by brbradford** [comment]
Any update on this issue? This could really solve a lot of headaches for us so we are anxiously awaiting this. Thanks for all your work on this project!

**Comment by darrenkopp** [comment]
Done. The alpha is on nuget.
